#spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dkzkepal1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 12490013980-9p8pbni6t94cuj6da8os0qei338fpmg7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 928366512040660
            client-secret: affa8b18df855893a0bb75abde6b90dd
            scope:
              - email
              - public_profile
          naver:
            client-id: 4gB9T1lHJhkPNZag1KZz
            client-secret: MW_KetUvhz
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해준다.

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
